project:
  type: website
  output-dir: docs

website:
  title: "E-Valuate - Auf dem Weg zum lernenden Staat"
  navbar:
    left:
      - href: index.qmd
        text: Herzlich Willkommen
      - bbn.qmd
      - blog.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

